version: "3.7"

services:
  db:
    # where to find it
    build: db
    # what to call it
    image: agasper01/k8s-and-heartbreak-db
  
  albums:
    build: albums
    image: agasper01/k8s-and-heartbreak-api
    deploy:
      replicas: 5

  web:
    build: web
    image: agasper01/k8s-and-heartbreak-web
    ports:
      - "8080:80"




# agasper01/k8s-and-heartbreak-web:latest
# agasper01/k8s-and-heartbreak-api:latest
# agasper01/k8s-and-heartbreak-db:latest