apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: k8s-and-heartbreak
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: k8s-and-hearbreak-db
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: k8s-and-heartbreak
spec:
  template:
    metadata:
      labels:
        app: k8s-and-heartbreak-db
    spec:
      containers:
        - name: db
          image: agasper01/k8s-and-heartbreak-db
          ports:
          - containerPort: 5432
            name: db
---
apiVersion: v1
kind: Service
metadata:
  name: albums
  labels:
    app: albums-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: albums-api
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: albums
  labels:
    app: albums-api
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: albums-api
    spec:
      containers:
      - name: albums
        image: agasper01/k8s-and-heartbreak-api:latest
        ports:
        - containerPort: 8080
          name: api
---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: k8s-and-heartbreak-web
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: web
  selector:
    app: k8s-and-heartbreak-web
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: k8s-and-heartbreak-web
spec:
  template:
    metadata:
      labels:
        app: k8s-and-heartbreak-web
    spec:
      containers:
      - name: web
        image: agasper01/k8s-and-heartbreak-web:latest
        ports:
        - containerPort: 80
        name: k8s-and-heartbreak-web